// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)

#define ZOLTAN_STRINGISE(N) #N
#define ZOLTAN_EXPAND_THEN_STRINGISE(N) ZOLTAN_STRINGISE(N)
#define __LINE_STR__ ZOLTAN_EXPAND_THEN_STRINGISE(__LINE__)

#ifndef AssertionFailed_Addr
#define AssertionFailed_Addr 0x2BCD3F0
#endif
#ifndef Breakpoint_Addr
#define Breakpoint_Addr 0x287B30
#endif
#ifndef CrashFunc_Addr
#define CrashFunc_Addr 0x2BD0680
#endif
#ifndef DebugPrint_Addr
#define DebugPrint_Addr 0xA97C60
#endif
#ifndef InvokeStatic_Addr
#define InvokeStatic_Addr 0x288640
#endif
#ifndef InvokeVirtual_Addr
#define InvokeVirtual_Addr 0x289F20
#endif
#ifndef Murmur3_32_Addr
#define Murmur3_32_Addr 0x276960
#endif
#ifndef ScriptHost_Get_Addr
#define ScriptHost_Get_Addr 0x275ED0
#endif
#ifndef ScriptHost_VFT_Addr
#define ScriptHost_VFT_Addr 0x3127DC0
#endif
#ifndef ScriptInterface_VFT_Addr
#define ScriptInterface_VFT_Addr 0x3127E60
#endif
#ifndef ShowMessageBox_Addr
#define ShowMessageBox_Addr 0xA7FB40
#endif
